LOG_FILE: 'logs/manage.log'  # path to log file or empty to log to console
LOG_LEVEL: 20  # python logging level
LOG_FORMAT: '%(asctime)-15s | %(name)-10s | %(levelname)-8s | %(message)s'  # python logging level

FAN_PIN: PC5  # identifier of control pin in SUNXI pinout

SLEEP_DURATION_SEC: 10  # time between check temperature

TIMEZONE: Europe/Moscow  # timezone for correct work schedule

SCHEDULE:  # schedule of manager
  BASE_POLICY:  # policy if not specified policy for current time
    THRESHOLD_ENABLE: 40  # temperature when enable fan
    THRESHOLD_DISABLE: 30  # temperature when disable fan
  SPECIAL_POLICIES:
    - TIME_START: 20h
      TIME_FINISH: 2h
      THRESHOLD_ENABLE: 55
      THRESHOLD_DISABLE: 45
    - TIME_START: 2h
      TIME_FINISH: 8h
      THRESHOLD_ENABLE: 45
      THRESHOLD_DISABLE: 35
